name: Deploy

on:
    push:
        branches:
            - main

jobs:
    deploy_lambda:
        runs-on: ubuntu-latest
        environment:
            name: production
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 20

            - name: Install dependencies
              run: npm ci
              env:
                  CI: true

            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: us-east-1

            - name: Deploy to AWS Lambda
              run: |
                  zip -r lambda.zip index.js node_modules
                  aws lambda update-function-code --function-name=${{ secrets.AWS_LAMBDA_FUNCTION_NAME }} --zip-file=fileb://lambda.zip
                  aws lambda wait function-updated --function-name=${{ secrets.AWS_LAMBDA_FUNCTION_NAME }}
                  aws lambda update-function-configuration --function-name=${{ secrets.AWS_LAMBDA_FUNCTION_NAME }} --environment "Variables={GMAIL_USER=${{ secrets.GMAIL_USER }},GMAIL_PASS=${{ secrets.GMAIL_PASS}}}"
