name: Deploy

on:
    push:
        branches:
            - main

jobs:
    deploy_lambda:
        runs-on: ubuntu-latest
        environment:
            name: production
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 20

            - name: Set environment variables
              env:
                  GMAIL_USER: ${{ secrets.GMAIL_USER }}
                  GMAIL_PASS: ${{ secrets.GMAIL_PASS }}
              run: |
                  echo "GMAIL_USER=$GMAIL_USER"
                  echo "GMAIL_PASS=$GMAIL_PASS"

            - name: Install dependencies
              run: npm ci
              env:
                  CI: true

            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: us-east-1

            - name: Deploy to AWS Lambda
              run: |
                  zip index.zip index.js
                  aws lambda update-function-code --function-name=greg-hosking-github-io-lambda --zip-file=fileb://index.zip
